language: java
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: "ischuros-github"
    token:
      secure: "J4Ptulr2XQCbJ4hGQzQC30WlhcyA/+McWKqxCkOTvuEfaqCybL0CdJ9sxDVDX8jRqvbJ8Nz5WO68A2a/qn5KMPJAtZ9P5SyuE33b7Erh/TpS1StzCErE9JRYBj3kyK0PjOeZrCVcKJixzPkxZT3ZJbrJbvXaROn5jE/FaAH1iznsZWniv4qdPAybxR4GiS0M1XZvBNRBnuy02MCfr/gHP3G6NFKxe3PgHGOAPfjFMmwSMroHKpnYaSeMpcPFFQL6fZIo+X9sCpvm4YmvYvK4wj1iD1OpRMjyp22VpAiVA33+R+LGRLFYK+oQhXIjlw8aroon6xAksLnwcMDe3AzogJd+tVcpLlxB0uzfvN0n5m/GGQARD6D7JJECBt91oXxz7zGhh/rUpNX3obihg1gk+zohRRM0b7ZcVtpilbvQ5tUmUltFol4HsCJTunTBC+O/2jkTKcVi2e76XudzPFyu3BGgGiIbN1e6SKPeWC0uQW/Sq74MNeLkkmWU4tQ/7MCv5z93W4mR0nDgKJhcHuncd4DNZ9JPWPX2U9pLyexrrzfkhSHPJqcATjUqrGTUjmwDQnwJilckGQxo4gQfX2vW10P/R9B+UbmdrRFMlLKvrPRQoOeWnJx82pfMa6X8y4ksiKQv/Vq3qaCdWw/knGBrB4N7j1DgK9jkwr5nbDRRDJM="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'