language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "ischuros-github"
    token:
        secure: "VCUJo67BOQEd+5MEDo4H1oEN1z/Zrhyod44e5cOuHFq3gEfOPJqVYSxZ+eUI2FDnjd//Pa1AXuxLvsFlA9vaMkpjK3Vm1aJBDImEyfB7qKCY2kpLpx/D0qVFEL0JGDgQVDoXW9P7Zk3bnsYGrAxwbh1F/XRFMPiXYwx7VlcfwJk5puR9wBIpvwteOP2cx/SfzQO5WKTxva3WOYc23HagWHiQChw2dlRD7eQw63FDYpM+sYNTjpGDltba8jZPJQHm/fy6hw3BBd87q9Dks/0boYHNh+bZScJwjj/BKe1kf4PPR3bY8Gwmlx5Sa9tHzdfDbmJputMkpJVABknnLqr/ldcUQ51bbbFyt6HNi2KYeg0Yy9bK99kZ2IzHAQCPCOSsbO7mBiy6qgkhQE9v3I7gUuqQL2S8twQB9HGrIfqXM5K9ITvAJiwKavnAraA09oFY8M8WZgStHQVwJYmPY/W940r7vub3NikR/9JiqKgGTjeL2ctbxLBy2wD+aOoR5DRUxZ9LXpRTKiID9aq9I5PrrgzVw7/vIbFReW3jN+Fz/0hM1xKOfpSVm/VTdW7J4nCWb75xhlh3yimi4f/oxxp895lwmAKNQmmUSBt8E4iCWZVwSbA8W+hhqTOgKcOOXHHWE0HIjdecfjh11rYc4ZXV109wXxsgxd09JbPZtcV50ck="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'