language: java
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: "ischuros"
    token:
        secure: "GoSJ9inIrNUnYzskFyiDFThALj/n5KgdemuD7WgKeEHMAbav29dd2h/bbyPI9zS7F9zff9kJwjnmjUL4WcX7FA9KISQkuuxP5tZXA5tHlwxWLw3cMB0bBXYdFGMBsyLV4JlD9eA/BYrGdC/VAy8BaYXn6DMPiXg3aAV3ydchXrTwf58lvovZrR0ZQd4aqaRZ4LbtidH/v5PzczXBx64EezaITLFpU6QbeGrrgD0RNkr73vw29zYpsBX+kFG5T+e49sSHgnSsjDd2kqFSvLNl0UfMwlHkgOciiG6KLe7nVoZhe4l62kQOJIp0duRqLYMOAY4J2scTAyUjZtFPlxUi1cAyqb7NSHb9F9EEQ7Cc32smAAYODpzUgmTISd85i2f/AztV/Qg/Ixmu8hi507POQLBdWTHnD5xEnWeX3uiAtGj1nhJlM0n5o/Jwyihqrxao95TxecWSAqhIkr3fWRiIEzu7KnkUv4/v+fQwMT2APP2fJmZp9pd5bLVZcoeCHyx10hQaCh4qlct6rGlWtxTOO1uZn5c2cwwsv3R2v6YSDWICCIvnHg+ES5UohyO52xONFU9hgUDsfEywg4MYIow3dP4LT9Ak12rSjJrZqcWzesnNl2YReIig2ADk8l/v9zdYATUXpPKzbA798dCx7dZtVnwHPjtlSnyW/H50gXFKS58="
script: "mvn clean verify && mvn test -B && mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar"